### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by akirmse** [tianhuil/domain_scheduler#1]
Looks like a good idea and something I've been looking for, too.  Two ideas:

- Migrate to Python 3

- Fix command in README.md:
pip install git+https://github.com/github.com/tianhuil/domain_scheduler.git@master

(github.com listed twice)

**Comment by tianhuil** [comment]
Thanks!  Please feel free to submit a pull request.

**Comment by tianhuil** [comment]
Being resolved in https://github.com/tianhuil/domain_scheduler/pull/2
